volumes:
  postgres_volume:

services:
  db:
    container_name: db
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
