[package]
name = "sly_window_state"
version = "0.1.0"
edition = "2021"

[features]
default = []


[dependencies]
bevy.workspace = true
bevy-persistent = { version = "0.7.0", features = ["ron"] }
serde.workspace = true
dirs = "5.0"