[package]
name = "billboard"
version.workspace = true
edition.workspace = true

[dependencies]
smallvec = "1.11.0"
bitflags = "2.3"


bevy.workspace = true


# see bevy #16563
#bevy_internal = { version = "0.15", features = ["bevy_image"] }