#https://github.com/uuid-rs/uuid/issues/792

#[target.wasm32-unknown-unknown]
#rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[build]
#target = "x86_64-unknown-linux-gnu" # or whatever
#rustflags = ["--cfg=has_std"]

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]