
[alias] # command aliases
b = ["leptos", "build"]
r = ["leptos", "build", "--release", "--features", "all_games"]
w = ["leptos", "watch"]
tic = ["run", "-p", "tic_tac_toe"]
breakout = ["run", "-p", "breakout"]

#https://github.com/leptos-rs/leptos/issues/1059
#https://book.leptos.dev/deployment/binary_size.html?highlight=build#things-to-do
#https://github.com/uuid-rs/uuid/issues/792

#[target.wasm32-unknown-unknown]
#rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

# [build]
# target = "x86_64-unknown-linux-gnu"

#[unstable]
#build-std = ["std", "panic_abort", "core", "alloc"]
#build-std-features = ["panic_immediate_abort"]

#https://bevyengine.org/learn/quick-start/getting-started/setup/#cranelift
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    #"link-arg=-fuse-ld=mold", 
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
]

# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"


[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"