[package]
name = "bus"
version = "0.1.0"
edition = "2021"

[features]
default = []
wayland = []

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui.workspace = true
serde = { workspace = true, features = ["derive"] }
crossbeam-channel = "0.5.13"

